trigger:
  branches:
    include:
      - '*'

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          echo '##vso[task.setvariable variable=PATH]$(PATH):$(HOME)/.cargo/bin'
        displayName: install rustup
      - script: |
          rustup component add rustfmt
        displayName: install rustfmt
      - script: |
          cargo fmt -- --check
        displayName: cargo fmt
      - script: |
          cargo test
        displayName: cargo test
      - script: |
          cargo build --verbose
        displayName: cargo build

  - job: macOS
    pool:
      vmImage: 'macos-10.14'
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          echo '##vso[task.setvariable variable=PATH]$(PATH):$(HOME)/.cargo/bin'
        displayName: install rustup
      - script: |
          rustup component add rustfmt
        displayName: install rustfmt
      - script: |
          cargo fmt -- --check
        displayName: cargo fmt
      - script: |
          cargo test
        displayName: cargo test
      - script: |
          cargo build --verbose
        displayName: cargo build

  - job: Windows
    pool:
      vmImage: 'windows-2019'
    steps:
      - script: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -y --default-toolchain stable
          set PATH=%PATH%;%USERPROFILE%\.cargo\bin
          echo '##vso[task.setvariable variable=PATH]%PATH%;%USERPROFILE%\.cargo\bin'
        displayName: install rustup
      - script: |
          rustup component add rustfmt
        displayName: install rustfmt
      - script: |
          cargo fmt -- --check
        displayName: cargo fmt
      - script: |
          cargo test
        displayName: cargo test
      - script: |
          cargo build --verbose
        displayName: cargo build
